package Entity;
// Generated Nov 1, 2016 5:03:19 PM by Hibernate Tools 5.2.0.Beta1

/**
 * UsercontrollernotificationId generated by hbm2java
 */
public class UsercontrollernotificationId implements java.io.Serializable {
	private static final long serialVersionUID = 905219423067508605L;
	private String username;
	private String controllername;

	public UsercontrollernotificationId() {
	}

	public UsercontrollernotificationId(String username, String controllername) {
		this.username = username;
		this.controllername = controllername;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getControllername() {
		return this.controllername;
	}

	public void setControllername(String controllername) {
		this.controllername = controllername;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof UsercontrollernotificationId))
			return false;
		UsercontrollernotificationId castOther = (UsercontrollernotificationId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getControllername() == castOther.getControllername())
						|| (this.getControllername() != null && castOther.getControllername() != null
								&& this.getControllername().equals(castOther.getControllername())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getControllername() == null ? 0 : this.getControllername().hashCode());
		return result;
	}

}
