# Generated by Django 2.1.5 on 2019-03-27 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reading',
            new_name='SensorReading',
        ),
    ]
