# Generated by Django 2.1.5 on 2019-03-31 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('definitions', '0002_auto_20190327_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='floor_plan',
            field=models.TextField(),
        ),
    ]
