# Generated by Django 2.1.5 on 2019-03-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('definitions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SensorTriggerSensor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='definitions.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='SimpleTrigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyScheduleDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week_start', models.IntegerField()),
                ('day_of_week_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DaySpecificSchedule',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.Schedule')),
            ],
            bases=('automation.schedule',),
        ),
        migrations.CreateModel(
            name='DaySpecificScheduleLine',
            fields=[
                ('scheduleline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.ScheduleLine')),
                ('day', models.DateField()),
                ('remark', models.TextField()),
                ('on_schedule_actuator_status', models.TextField()),
                ('post_schedule_actuator_status', models.TextField()),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.DaySpecificSchedule')),
            ],
            bases=('automation.scheduleline',),
        ),
        migrations.CreateModel(
            name='SensorTrigger',
            fields=[
                ('simpletrigger_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.SimpleTrigger')),
                ('expression', models.TextField()),
                ('threshold_value', models.FloatField()),
                ('threshold_operator', models.CharField(max_length=2)),
            ],
            bases=('automation.simpletrigger',),
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('schedule_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.Schedule')),
            ],
            bases=('automation.schedule',),
        ),
        migrations.CreateModel(
            name='WeeklyScheduleDayTimeInterval',
            fields=[
                ('scheduleline_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='automation.ScheduleLine')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('remark', models.TextField()),
                ('on_schedule_actuator_status', models.TextField()),
                ('post_schedule_actuator_status', models.TextField()),
                ('schedule_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.WeeklyScheduleDay')),
            ],
            bases=('automation.scheduleline',),
        ),
        migrations.AddField(
            model_name='simpletrigger',
            name='schedule_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.ScheduleLine'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='actuator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='definitions.Actuator'),
        ),
        migrations.AddField(
            model_name='weeklyscheduleday',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.WeeklySchedule'),
        ),
        migrations.AddField(
            model_name='sensortriggersensor',
            name='sensor_trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automation.SensorTrigger'),
        ),
    ]
