package Chi;
import java.util.HashSet;
import java.util.Set;

/**
 * Actuator generated by hbm2java
 */
public class Actuator implements java.io.Serializable {
	private static final long serialVersionUID = 266627733957095016L;
	private String name;
	private Controller controller;
	private String status;
	private Double positionx;
	private Double positiony;
	private Set<Regularschedule> regularschedules = new HashSet<Regularschedule>(0);
	private Set<Specialschedule> specialschedules = new HashSet<Specialschedule>(0);

	public Actuator() {
	}

	public Actuator(String name) {
		this.name = name;
	}

	public Actuator(String name, Controller controller, String status, double positionx, double positiony,
			Set<Regularschedule> regularschedules,Set<Specialschedule> specialschedules) {
		this.name = name;
		this.controller = controller;
		this.status = status;
		this.positionx = positionx;
		this.positiony = positiony;
		this.regularschedules = regularschedules;
		this.specialschedules = specialschedules;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Controller getController() {
		return this.controller;
	}

	public void setController(Controller controller) {
		this.controller = controller;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Double getPositionx() {
		return this.positionx;
	}

	public void setPositionx(Double positionx) {
		this.positionx = positionx;
	}

	public Double getPositiony() {
		return this.positiony;
	}

	public void setPositiony(Double positiony) {
		this.positiony = positiony;
	}
	
	public Set<Regularschedule> getRegularschedules() {
		return this.regularschedules;
	}

	public void setRegularschedules(Set<Regularschedule> regularschedules) {
		this.regularschedules = regularschedules;
	}

	public Set<Specialschedule> getSpecialschedules() {
		return this.specialschedules;
	}

	public void setSpecialschedules(Set<Specialschedule> specialschedules) {
		this.specialschedules = specialschedules;
	}

	public Object [] toObj () {
		return new Object [] {this.getName(), this.getController(), this.getStatus(),this.positionx,this.positiony};
	}
}
