package Chi;
import java.util.HashSet;
import java.util.Set;

/**
 * Actuator generated by hbm2java
 */
public class Actuator implements java.io.Serializable {
	private static final long serialVersionUID = 266627733957095016L;
	private String name;
	private Controller controller;
	private String status;
	private Set<Regularschedule> regularschedules = new HashSet<Regularschedule>(0);
	private Set<Specialschedule> specialschedules = new HashSet<Specialschedule>(0);

	public Actuator() {
	}

	public Actuator(String name) {
		this.name = name;
	}

	public Actuator(String name, Controller controller, String status, Set<Regularschedule> regularschedules,
			Set<Specialschedule> specialschedules) {
		this.name = name;
		this.controller = controller;
		this.status = status;
		this.regularschedules = regularschedules;
		this.specialschedules = specialschedules;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Controller getController() {
		return this.controller;
	}

	public void setController(Controller controller) {
		this.controller = controller;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Set<Regularschedule> getRegularschedules() {
		return this.regularschedules;
	}

	public void setRegularschedules(Set<Regularschedule> regularschedules) {
		this.regularschedules = regularschedules;
	}

	public Set<Specialschedule> getSpecialschedules() {
		return this.specialschedules;
	}

	public void setSpecialschedules(Set<Specialschedule> specialschedules) {
		this.specialschedules = specialschedules;
	}

}
