package Chi;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Controller generated by hbm2java
 */
public class Controller implements java.io.Serializable {
	private static final long serialVersionUID = 7386807131288441489L;
	private String controllername;
	private Site site;
	private Double positionx;
	private Double positiony;
	private String ipaddress;
	private Integer reporttimeout;
	private Date lastreporttime;
	private Set<Controllerevent> controllerevents = new HashSet<Controllerevent>(0);
	private Set<Sensor> sensors = new HashSet<Sensor>(0);
	private Set<Actuator> actuators = new HashSet<Actuator>(0);

	public Controller() {
	}

	public Controller(String controllername) {
		this.controllername = controllername;
	}

	public Controller(String controllername, Site site, Double positionx, Double positiony, String ipaddress,
			Integer reporttimeout, Date lastreporttime, Set<Controllerevent> controllerevents, Set<Sensor> sensors,
			Set<Actuator> actuators) {
		this.controllername = controllername;
		this.site = site;
		this.positionx = positionx;
		this.positiony = positiony;
		this.ipaddress = ipaddress;
		this.reporttimeout = reporttimeout;
		this.lastreporttime = lastreporttime;
		this.controllerevents = controllerevents;
		this.sensors = sensors;
		this.actuators = actuators;
	}

	public String getControllername() {
		return this.controllername;
	}

	public void setControllername(String controllername) {
		this.controllername = controllername;
	}

	public Site getSite() {
		return this.site;
	}

	public void setSite(Site site) {
		this.site = site;
	}

	public Double getPositionx() {
		return this.positionx;
	}

	public void setPositionx(Double positionx) {
		this.positionx = positionx;
	}

	public Double getPositiony() {
		return this.positiony;
	}

	public void setPositiony(Double positiony) {
		this.positiony = positiony;
	}

	public String getIpaddress() {
		return this.ipaddress;
	}

	public void setIpaddress(String ipaddress) {
		this.ipaddress = ipaddress;
	}
	
	public Integer getReporttimeout() {
		return this.reporttimeout;
	}

	public void setReporttimeout(Integer reporttimeout) {
		this.reporttimeout = reporttimeout;
	}

	public Date getLastreporttime() {
		return this.lastreporttime;
	}

	public void setLastreporttime(Date lastreporttime) {
		this.lastreporttime = lastreporttime;
	}

	public void setControllerevents(Set<Controllerevent> controllerevents) {
		this.controllerevents = controllerevents;
	}
	
	public Set<Controllerevent> getControllerevents() {
		return this.controllerevents;
	}
	
	public Set<Sensor> getSensors() {
		return this.sensors;
	}

	public void setSensors(Set<Sensor> sensors) {
		this.sensors = sensors;
	}

	public Set<Actuator> getActuators() {
		return this.actuators;
	}
	
	public void setActuators(Set<Actuator> actuators) {
		this.actuators = actuators;
	}

	public Object [] toObj () {
		return new Object [] {this.getControllername(), this.getSite().getSitename(),
							  this.getPositionx(), this.getPositiony(),
							  this.getReporttimeout(), this.getLastreporttime()};
	}
}
