package Chi;
/**
 * Sensor generated by hbm2java
 */
public class Sensor implements java.io.Serializable {
	private static final long serialVersionUID = -8309734046585614076L;
	private String sensorname;
	private Controller controller;
	private Sensorclass sensorclass;
	private Double minvalue;
	private Double maxvalue;
	private Double transformationfactor;
	private String unit;

	public Sensor() {
	}

	public Sensor(String sensorname) {
		this.sensorname = sensorname;
	}

	public Sensor(String sensorname, Controller controller, Sensorclass sensorclass, Double minvalue, Double maxvalue,
			Double transformationfactor, String unit) {
		this.sensorname = sensorname;
		this.controller = controller;
		this.sensorclass = sensorclass;
		this.minvalue = minvalue;
		this.maxvalue = maxvalue;
		this.transformationfactor = transformationfactor;
		this.unit = unit;
	}

	public String getSensorname() {
		return this.sensorname;
	}

	public void setSensorname(String sensorname) {
		this.sensorname = sensorname;
	}

	public Controller getController() {
		return this.controller;
	}

	public void setController(Controller controller) {
		this.controller = controller;
	}

	public Sensorclass getSensorclass() {
		return this.sensorclass;
	}

	public void setSensorclass(Sensorclass sensorclass) {
		this.sensorclass = sensorclass;
	}

	public Double getMinvalue() {
		return this.minvalue;
	}

	public void setMinvalue(Double minvalue) {
		this.minvalue = minvalue;
	}

	public Double getMaxvalue() {
		return this.maxvalue;
	}

	public void setMaxvalue(Double maxvalue) {
		this.maxvalue = maxvalue;
	}

	public Double getTransformationfactor() {
		return this.transformationfactor;
	}

	public void setTransformationfactor(Double transformationfactor) {
		this.transformationfactor = transformationfactor;
	}

	public String getUnit() {
		return this.unit;
	}

	public void setUnit(String unit) {
		this.unit = unit;
	}

}
