package Chi;
import java.util.HashSet;
import java.util.Set;

/**
 * Site generated by hbm2java
 */
public class Site implements java.io.Serializable {
	private static final long serialVersionUID = 3862237986678674953L;
	private String sitename;
	private String sitemapurl;
	private Set<Controller> controllers = new HashSet<Controller>(0);

	public Site() {
	}

	public Site(String sitename) {
		this.sitename = sitename;
	}

	public Site(String sitename, String sitemapurl, Set<Controller> controllers) {
		this.sitename = sitename;
		this.sitemapurl = sitemapurl;
		this.controllers = controllers;
	}

	public String getSitename() {
		return this.sitename;
	}

	public void setSitename(String sitename) {
		this.sitename = sitename;
	}

	public String getSitemapurl() {
		return this.sitemapurl;
	}

	public void setSitemapurl(String sitemapurl) {
		this.sitemapurl = sitemapurl;
	}

	public Set<Controller> getControllers() {
		return this.controllers;
	}

	public void setControllers(Set<Controller> controllers) {
		this.controllers = controllers;
	}

}
